AWSTemplateFormatVersion: 2010-09-09
Description: Creates a VPC with public and private subnets 
Resources:
  VPC: 
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 192.168.100.0/24
  PublicSubnetA: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: "eu-central-1a" 
      CidrBlock: 192.168.100.0/28
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
  PrivateSubnetB: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: "eu-central-1a"
      CidrBlock: 192.168.100.32/28
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-0c6819469cfeec553"
      KeyName: "raghda_keypair"
      InstanceType: t2.micro
      SubnetId: !Ref PublicSubnetA
      SecurityGroupIds: 
        - !Ref SecurityGroup   

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow HTTP and SSH Access"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"    
